# yaml-language-server: $schema=https://github.com/adobe-platform/kubernetes-json-schema/raw/refs/heads/master/master-standalone/application-argoproj-v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vertical-pod-autoscaler
  namespace: argocd
spec:
  project: homelab
  sources:
    # https://artifacthub.io/packages/helm/cluster-autoscaler/vertical-pod-autoscaler
    - repoURL: https://kubernetes.github.io/autoscaler
      chart: vertical-pod-autoscaler
      targetRevision: 0.8.0
      helm:
        releaseName: vertical-pod-autoscaler
        valuesObject:
          # Only one node so far, one replica (also avoids anti-affinity issues)
          admissionController:
            replicas: 1
          recommender:
            replicas: 1
            podAnnotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: 8942
              prometheus.io/path: /metrics
              prometheus.io/scheme: http
          updater:
            replicas: 1
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
