server:
  extraFlags:
    - web.enable-remote-write-receiver
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    paths:
      - /
    hosts:
      - prometheus.home.pontifex.dev
    tls:
      - secretName: prometheus-home-pontifex-dev-tls
        hosts:
          - prometheus.home.pontifex.dev

# Both of these provided by the k8s-monitoring chart
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: true

scrapeConfigs:
  kubernetes-api-servers:
    enabled: false
  kubernetes-nodes:
    enabled: false
  kubernetes-pods:
    enabled: false
  kubernetes-cadvisor:
    enabled: false
  kubernetes-service-endpoints:
    enabled: false
  kubernetes-services:
    enabled: false
  kubernetes-ingress-endpoints:
    enabled: false
  kubernetes-ingresses:
    enabled: false
