# yaml-language-server: $schema=https://github.com/grafana/k8s-monitoring-helm/raw/refs/heads/main/charts/k8s-monitoring/values.schema.json
cluster:
  name: homelab

destinations:
  - name: loki
    type: loki
    url: http://loki-gateway.monitoring.svc.cluster.local:3100

clusterMetrics:
  enabled: false # No metrics destinations yet
clusterEvents:
  enabled: true
nodeLogs:
  enabled: true
podLogs:
  enabled: true
